// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8brCYiXF3tJu7iHYu8Tj1aXKfmfSqXeE',
    appId: '1:67439304696:android:94f82b7d4888395ae7800d',
    messagingSenderId: '67439304696',
    projectId: 'note-system-9d1f',
    storageBucket: 'note-system-9d1f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7xibdfxoPxtYtR5VXJRCBoDdkwjXn3Q',
    appId: '1:67439304696:web:1f5be8e08f12b8b7e7800d',
    messagingSenderId: '67439304696',
    projectId: 'note-system-9d1f',
    authDomain: 'note-system-9d1f.firebaseapp.com',
    storageBucket: 'note-system-9d1f.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7xibdfxoPxtYtR5VXJRCBoDdkwjXn3Q',
    appId: '1:67439304696:web:1f5be8e08f12b8b7e7800d',
    messagingSenderId: '67439304696',
    projectId: 'note-system-9d1f',
    authDomain: 'note-system-9d1f.firebaseapp.com',
    storageBucket: 'note-system-9d1f.firebasestorage.app',
  );
}
